const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  await prisma.character.createMany({
    data: [
      {
        id: '1001',
        name: 'March 7th',
        tag: 'mar7th',
        rarity: 4,
        path: 'Knight',
        element: 'Ice',
        icon: 'icon/character/1001.png',
        preview: 'image/character_preview/1001.png',
        portrait: 'image/character_portrait/1001.png',
      },
      {
        id: '1002',
        name: 'Dan Heng',
        tag: 'danheng',
        rarity: 4,
        path: 'Rogue',
        element: 'Wind',
        icon: 'icon/character/1002.png',
        preview: 'image/character_preview/1002.png',
        portrait: 'image/character_portrait/1002.png',
      },
      {
        id: '1003',
        name: 'Himeko',
        tag: 'himeko',
        rarity: 5,
        path: 'Mage',
        element: 'Fire',
        icon: 'icon/character/1003.png',
        preview: 'image/character_preview/1003.png',
        portrait: 'image/character_portrait/1003.png',
      },
      {
        id: '1004',
        name: 'Welt',
        tag: 'welt',
        rarity: 5,
        path: 'Warlock',
        element: 'Imaginary',
        icon: 'icon/character/1004.png',
        preview: 'image/character_preview/1004.png',
        portrait: 'image/character_portrait/1004.png',
      },
      {
        id: '1005',
        name: 'Kafka',
        tag: 'kafka',
        rarity: 5,
        path: 'Warlock',
        element: 'Thunder',
        icon: 'icon/character/1005.png',
        preview: 'image/character_preview/1005.png',
        portrait: 'image/character_portrait/1005.png',
      },
      {
        id: '1006',
        name: 'S\u00f3i B\u1ea1c',
        tag: 'silverwolf',
        rarity: 5,
        path: 'Warlock',
        element: 'Quantum',
        icon: 'icon/character/1006.png',
        preview: 'image/character_preview/1006.png',
        portrait: 'image/character_portrait/1006.png',
      },
      {
        id: '1008',
        name: 'Arlan',
        tag: 'arlan',
        rarity: 4,
        path: 'Warrior',
        element: 'Thunder',
        icon: 'icon/character/1008.png',
        preview: 'image/character_preview/1008.png',
        portrait: 'image/character_portrait/1008.png',
      },
      {
        id: '1009',
        name: 'Asta',
        tag: 'asta',
        rarity: 4,
        path: 'Shaman',
        element: 'Fire',
        icon: 'icon/character/1009.png',
        preview: 'image/character_preview/1009.png',
        portrait: 'image/character_portrait/1009.png',
      },
      {
        id: '1013',
        name: 'Herta',
        tag: 'herta',
        rarity: 4,
        path: 'Mage',
        element: 'Ice',
        icon: 'icon/character/1013.png',
        preview: 'image/character_preview/1013.png',
        portrait: 'image/character_portrait/1013.png',
      },
      {
        id: '1101',
        name: 'Bronya',
        tag: 'bronya',
        rarity: 5,
        path: 'Shaman',
        element: 'Wind',
        icon: 'icon/character/1101.png',
        preview: 'image/character_preview/1101.png',
        portrait: 'image/character_portrait/1101.png',
      },
      {
        id: '1102',
        name: 'Seele',
        tag: 'seele',
        rarity: 5,
        path: 'Rogue',
        element: 'Quantum',
        icon: 'icon/character/1102.png',
        preview: 'image/character_preview/1102.png',
        portrait: 'image/character_portrait/1102.png',
      },
      {
        id: '1103',
        name: 'Serval',
        tag: 'serval',
        rarity: 4,
        path: 'Mage',
        element: 'Thunder',
        icon: 'icon/character/1103.png',
        preview: 'image/character_preview/1103.png',
        portrait: 'image/character_portrait/1103.png',
      },
      {
        id: '1104',
        name: 'Gepard',
        tag: 'gepard',
        rarity: 5,
        path: 'Knight',
        element: 'Ice',
        icon: 'icon/character/1104.png',
        preview: 'image/character_preview/1104.png',
        portrait: 'image/character_portrait/1104.png',
      },
      {
        id: '1105',
        name: 'Natasha',
        tag: 'natasha',
        rarity: 4,
        path: 'Priest',
        element: 'Physical',
        icon: 'icon/character/1105.png',
        preview: 'image/character_preview/1105.png',
        portrait: 'image/character_portrait/1105.png',
      },
      {
        id: '1106',
        name: 'Pela',
        tag: 'pela',
        rarity: 4,
        path: 'Warlock',
        element: 'Ice',
        icon: 'icon/character/1106.png',
        preview: 'image/character_preview/1106.png',
        portrait: 'image/character_portrait/1106.png',
      },
      {
        id: '1107',
        name: 'Clara',
        tag: 'clara',
        rarity: 5,
        path: 'Warrior',
        element: 'Physical',
        icon: 'icon/character/1107.png',
        preview: 'image/character_preview/1107.png',
        portrait: 'image/character_portrait/1107.png',
      },
      {
        id: '1108',
        name: 'Sampo',
        tag: 'sampo',
        rarity: 4,
        path: 'Warlock',
        element: 'Wind',
        icon: 'icon/character/1108.png',
        preview: 'image/character_preview/1108.png',
        portrait: 'image/character_portrait/1108.png',
      },
      {
        id: '1109',
        name: 'Hook',
        tag: 'hook',
        rarity: 4,
        path: 'Warrior',
        element: 'Fire',
        icon: 'icon/character/1109.png',
        preview: 'image/character_preview/1109.png',
        portrait: 'image/character_portrait/1109.png',
      },
      {
        id: '1110',
        name: 'Lynx',
        tag: 'lynx',
        rarity: 4,
        path: 'Priest',
        element: 'Quantum',
        icon: 'icon/character/1110.png',
        preview: 'image/character_preview/1110.png',
        portrait: 'image/character_portrait/1110.png',
      },
      {
        id: '1111',
        name: 'Luka',
        tag: 'luka',
        rarity: 4,
        path: 'Warlock',
        element: 'Physical',
        icon: 'icon/character/1111.png',
        preview: 'image/character_preview/1111.png',
        portrait: 'image/character_portrait/1111.png',
      },
      {
        id: '1112',
        name: 'Topaz & Numby',
        tag: 'topaz',
        rarity: 5,
        path: 'Rogue',
        element: 'Fire',
        icon: 'icon/character/1112.png',
        preview: 'image/character_preview/1112.png',
        portrait: 'image/character_portrait/1112.png',
      },
      {
        id: '1201',
        name: 'Qingque',
        tag: 'qingque',
        rarity: 4,
        path: 'Mage',
        element: 'Quantum',
        icon: 'icon/character/1201.png',
        preview: 'image/character_preview/1201.png',
        portrait: 'image/character_portrait/1201.png',
      },
      {
        id: '1202',
        name: 'Tingyun',
        tag: 'tingyun',
        rarity: 4,
        path: 'Shaman',
        element: 'Thunder',
        icon: 'icon/character/1202.png',
        preview: 'image/character_preview/1202.png',
        portrait: 'image/character_portrait/1202.png',
      },
      {
        id: '1203',
        name: 'Luocha',
        tag: 'luocha',
        rarity: 5,
        path: 'Priest',
        element: 'Imaginary',
        icon: 'icon/character/1203.png',
        preview: 'image/character_preview/1203.png',
        portrait: 'image/character_portrait/1203.png',
      },
      {
        id: '1204',
        name: 'Jing Yuan',
        tag: 'jingyuan',
        rarity: 5,
        path: 'Mage',
        element: 'Thunder',
        icon: 'icon/character/1204.png',
        preview: 'image/character_preview/1204.png',
        portrait: 'image/character_portrait/1204.png',
      },
      {
        id: '1205',
        name: 'Blade',
        tag: 'blade',
        rarity: 5,
        path: 'Warrior',
        element: 'Wind',
        icon: 'icon/character/1205.png',
        preview: 'image/character_preview/1205.png',
        portrait: 'image/character_portrait/1205.png',
      },
      {
        id: '1206',
        name: 'Sushang',
        tag: 'sushang',
        rarity: 4,
        path: 'Rogue',
        element: 'Physical',
        icon: 'icon/character/1206.png',
        preview: 'image/character_preview/1206.png',
        portrait: 'image/character_portrait/1206.png',
      },
      {
        id: '1207',
        name: 'Yukong',
        tag: 'yukong',
        rarity: 4,
        path: 'Shaman',
        element: 'Imaginary',
        icon: 'icon/character/1207.png',
        preview: 'image/character_preview/1207.png',
        portrait: 'image/character_portrait/1207.png',
      },
      {
        id: '1208',
        name: 'Fu Xuan',
        tag: 'fuxuan',
        rarity: 5,
        path: 'Knight',
        element: 'Quantum',
        icon: 'icon/character/1208.png',
        preview: 'image/character_preview/1208.png',
        portrait: 'image/character_portrait/1208.png',
      },
      {
        id: '1209',
        name: 'Yanqing',
        tag: 'yanqing',
        rarity: 5,
        path: 'Rogue',
        element: 'Ice',
        icon: 'icon/character/1209.png',
        preview: 'image/character_preview/1209.png',
        portrait: 'image/character_portrait/1209.png',
      },
      {
        id: '1210',
        name: 'Guinaifen',
        tag: 'guinaifen',
        rarity: 4,
        path: 'Warlock',
        element: 'Fire',
        icon: 'icon/character/1210.png',
        preview: 'image/character_preview/1210.png',
        portrait: 'image/character_portrait/1210.png',
      },
      {
        id: '1211',
        name: 'Bailu',
        tag: 'bailu',
        rarity: 5,
        path: 'Priest',
        element: 'Thunder',
        icon: 'icon/character/1211.png',
        preview: 'image/character_preview/1211.png',
        portrait: 'image/character_portrait/1211.png',
      },
      {
        id: '1212',
        name: 'Jingliu',
        tag: 'jingliu',
        rarity: 5,
        path: 'Warrior',
        element: 'Ice',
        icon: 'icon/character/1212.png',
        preview: 'image/character_preview/1212.png',
        portrait: 'image/character_portrait/1212.png',
      },
      {
        id: '1213',
        name: 'Dan Heng - \u1ea8m Nguy\u1ec7t',
        tag: 'danhengil',
        rarity: 5,
        path: 'Warrior',
        element: 'Imaginary',
        icon: 'icon/character/1213.png',
        preview: 'image/character_preview/1213.png',
        portrait: 'image/character_portrait/1213.png',
      },
      {
        id: '1214',
        name: 'Xueyi',
        tag: 'xueyi',
        rarity: 4,
        path: 'Warrior',
        element: 'Quantum',
        icon: 'icon/character/1214.png',
        preview: 'image/character_preview/1214.png',
        portrait: 'image/character_portrait/1214.png',
      },
      {
        id: '1215',
        name: 'Hanya',
        tag: 'hanya',
        rarity: 4,
        path: 'Shaman',
        element: 'Physical',
        icon: 'icon/character/1215.png',
        preview: 'image/character_preview/1215.png',
        portrait: 'image/character_portrait/1215.png',
      },
      {
        id: '1217',
        name: 'Huohuo',
        tag: 'huohuo',
        rarity: 5,
        path: 'Priest',
        element: 'Wind',
        icon: 'icon/character/1217.png',
        preview: 'image/character_preview/1217.png',
        portrait: 'image/character_portrait/1217.png',
      },
      {
        id: '1218',
        name: 'Jiaoqiu',
        tag: 'jiaoqiu',
        rarity: 5,
        path: 'Warlock',
        element: 'Fire',
        icon: 'icon/character/1218.png',
        preview: 'image/character_preview/1218.png',
        portrait: 'image/character_portrait/1218.png',
      },
      {
        id: '1220',
        name: 'Feixiao',
        tag: 'feixiao',
        rarity: 5,
        path: 'Rogue',
        element: 'Wind',
        icon: 'icon/character/1220.png',
        preview: 'image/character_preview/1220.png',
        portrait: 'image/character_portrait/1220.png',
      },
      {
        id: '1221',
        name: 'Yunli',
        tag: 'yunli',
        rarity: 5,
        path: 'Warrior',
        element: 'Physical',
        icon: 'icon/character/1221.png',
        preview: 'image/character_preview/1221.png',
        portrait: 'image/character_portrait/1221.png',
      },
      {
        id: '1222',
        name: 'Lingsha',
        tag: 'lingsha',
        rarity: 5,
        path: 'Priest',
        element: 'Fire',
        icon: 'icon/character/1222.png',
        preview: 'image/character_preview/1222.png',
        portrait: 'image/character_portrait/1222.png',
      },
      {
        id: '1223',
        name: 'Moze',
        tag: 'moze',
        rarity: 4,
        path: 'Rogue',
        element: 'Thunder',
        icon: 'icon/character/1223.png',
        preview: 'image/character_preview/1223.png',
        portrait: 'image/character_portrait/1223.png',
      },
      {
        id: '1224',
        name: 'March 7th',
        tag: 'mar7th2',
        rarity: 4,
        path: 'Rogue',
        element: 'Imaginary',
        icon: 'icon/character/1224.png',
        preview: 'image/character_preview/1224.png',
        portrait: 'image/character_portrait/1224.png',
      },
      {
        id: '1225',
        name: 'Fugue',
        tag: 'fugue',
        rarity: 5,
        path: 'Warlock',
        element: 'Fire',
        icon: 'icon/character/1225.png',
        preview: 'image/character_preview/1225.png',
        portrait: 'image/character_portrait/1225.png',
      },
      {
        id: '1301',
        name: 'Gallagher',
        tag: 'gallagher',
        rarity: 4,
        path: 'Priest',
        element: 'Fire',
        icon: 'icon/character/1301.png',
        preview: 'image/character_preview/1301.png',
        portrait: 'image/character_portrait/1301.png',
      },
      {
        id: '1302',
        name: 'Argenti',
        tag: 'argenti',
        rarity: 5,
        path: 'Mage',
        element: 'Physical',
        icon: 'icon/character/1302.png',
        preview: 'image/character_preview/1302.png',
        portrait: 'image/character_portrait/1302.png',
      },
      {
        id: '1303',
        name: 'Ruan Mei',
        tag: 'ruanmei',
        rarity: 5,
        path: 'Shaman',
        element: 'Ice',
        icon: 'icon/character/1303.png',
        preview: 'image/character_preview/1303.png',
        portrait: 'image/character_portrait/1303.png',
      },
      {
        id: '1304',
        name: 'Aventurine',
        tag: 'aventurine',
        rarity: 5,
        path: 'Knight',
        element: 'Imaginary',
        icon: 'icon/character/1304.png',
        preview: 'image/character_preview/1304.png',
        portrait: 'image/character_portrait/1304.png',
      },
      {
        id: '1305',
        name: 'Dr. Ratio',
        tag: 'drratio',
        rarity: 5,
        path: 'Rogue',
        element: 'Imaginary',
        icon: 'icon/character/1305.png',
        preview: 'image/character_preview/1305.png',
        portrait: 'image/character_portrait/1305.png',
      },
      {
        id: '1306',
        name: 'Sparkle',
        tag: 'sparkle',
        rarity: 5,
        path: 'Shaman',
        element: 'Quantum',
        icon: 'icon/character/1306.png',
        preview: 'image/character_preview/1306.png',
        portrait: 'image/character_portrait/1306.png',
      },
      {
        id: '1307',
        name: 'Black Swan',
        tag: 'blackswan',
        rarity: 5,
        path: 'Warlock',
        element: 'Wind',
        icon: 'icon/character/1307.png',
        preview: 'image/character_preview/1307.png',
        portrait: 'image/character_portrait/1307.png',
      },
      {
        id: '1308',
        name: 'Acheron',
        tag: 'acheron',
        rarity: 5,
        path: 'Warlock',
        element: 'Thunder',
        icon: 'icon/character/1308.png',
        preview: 'image/character_preview/1308.png',
        portrait: 'image/character_portrait/1308.png',
      },
      {
        id: '1309',
        name: 'Robin',
        tag: 'robin',
        rarity: 5,
        path: 'Shaman',
        element: 'Physical',
        icon: 'icon/character/1309.png',
        preview: 'image/character_preview/1309.png',
        portrait: 'image/character_portrait/1309.png',
      },
      {
        id: '1310',
        name: 'Firefly',
        tag: 'sam',
        rarity: 5,
        path: 'Warrior',
        element: 'Fire',
        icon: 'icon/character/1310.png',
        preview: 'image/character_preview/1310.png',
        portrait: 'image/character_portrait/1310.png',
      },
      {
        id: '1312',
        name: 'Misha',
        tag: 'misha',
        rarity: 4,
        path: 'Warrior',
        element: 'Ice',
        icon: 'icon/character/1312.png',
        preview: 'image/character_preview/1312.png',
        portrait: 'image/character_portrait/1312.png',
      },
      {
        id: '1313',
        name: 'Sunday',
        tag: 'sunday',
        rarity: 5,
        path: 'Shaman',
        element: 'Imaginary',
        icon: 'icon/character/1313.png',
        preview: 'image/character_preview/1313.png',
        portrait: 'image/character_portrait/1313.png',
      },
      {
        id: '1314',
        name: 'Jade',
        tag: 'jade',
        rarity: 5,
        path: 'Mage',
        element: 'Quantum',
        icon: 'icon/character/1314.png',
        preview: 'image/character_preview/1314.png',
        portrait: 'image/character_portrait/1314.png',
      },
      {
        id: '1315',
        name: 'Boothill',
        tag: 'boothill',
        rarity: 5,
        path: 'Rogue',
        element: 'Physical',
        icon: 'icon/character/1315.png',
        preview: 'image/character_preview/1315.png',
        portrait: 'image/character_portrait/1315.png',
      },
      {
        id: '1317',
        name: 'Rappa',
        tag: 'rappa',
        rarity: 5,
        path: 'Mage',
        element: 'Imaginary',
        icon: 'icon/character/1317.png',
        preview: 'image/character_preview/1317.png',
        portrait: 'image/character_portrait/1317.png',
      },
      {
        id: '1401',
        name: '\u0110\u1ea1i Herta',
        tag: 'theherta',
        rarity: 5,
        path: 'Mage',
        element: 'Ice',
        icon: 'icon/character/1401.png',
        preview: 'image/character_preview/1401.png',
        portrait: 'image/character_portrait/1401.png',
      },
      {
        id: '1402',
        name: 'Aglaea',
        tag: 'aglaea',
        rarity: 5,
        path: 'Memory',
        element: 'Thunder',
        icon: 'icon/character/1402.png',
        preview: 'image/character_preview/1402.png',
        portrait: 'image/character_portrait/1402.png',
      },
      {
        id: '1403',
        name: 'Tribbie',
        tag: 'tribbie',
        rarity: 5,
        path: 'Shaman',
        element: 'Quantum',
        icon: 'icon/character/1403.png',
        preview: 'image/character_preview/1403.png',
        portrait: 'image/character_portrait/1403.png',
      },
      {
        id: '1404',
        name: 'Mydei',
        tag: 'mydei',
        rarity: 5,
        path: 'Warrior',
        element: 'Imaginary',
        icon: 'icon/character/1404.png',
        preview: 'image/character_preview/1404.png',
        portrait: 'image/character_portrait/1404.png',
      },
      {
        id: '1405',
        name: 'Anaxa',
        tag: 'anaxa',
        rarity: 5,
        path: 'Mage',
        element: 'Wind',
        icon: 'icon/character/1405.png',
        preview: 'image/character_preview/1405.png',
        portrait: 'image/character_portrait/1405.png',
      },
      {
        id: '1407',
        name: 'Castorice',
        tag: 'castorice',
        rarity: 5,
        path: 'Memory',
        element: 'Quantum',
        icon: 'icon/character/1407.png',
        preview: 'image/character_preview/1407.png',
        portrait: 'image/character_portrait/1407.png',
      },
      {
        id: '8001',
        name: '{NICKNAME}',
        tag: 'playerboy',
        rarity: 5,
        path: 'Warrior',
        element: 'Physical',
        icon: 'icon/character/8001.png',
        preview: 'image/character_preview/8001.png',
        portrait: 'image/character_portrait/8001.png',
      },
      {
        id: '8002',
        name: '{NICKNAME}',
        tag: 'playergirl',
        rarity: 5,
        path: 'Warrior',
        element: 'Physical',
        icon: 'icon/character/8002.png',
        preview: 'image/character_preview/8002.png',
        portrait: 'image/character_portrait/8002.png',
      },
      {
        id: '8003',
        name: '{NICKNAME}',
        tag: 'playerboy2',
        rarity: 5,
        path: 'Knight',
        element: 'Fire',
        icon: 'icon/character/8003.png',
        preview: 'image/character_preview/8003.png',
        portrait: 'image/character_portrait/8003.png',
      },
      {
        id: '8004',
        name: '{NICKNAME}',
        tag: 'playergirl2',
        rarity: 5,
        path: 'Knight',
        element: 'Fire',
        icon: 'icon/character/8004.png',
        preview: 'image/character_preview/8004.png',
        portrait: 'image/character_portrait/8004.png',
      },
      {
        id: '8005',
        name: '{NICKNAME}',
        tag: 'playerboy3',
        rarity: 5,
        path: 'Shaman',
        element: 'Imaginary',
        icon: 'icon/character/8005.png',
        preview: 'image/character_preview/8005.png',
        portrait: 'image/character_portrait/8005.png',
      },
      {
        id: '8006',
        name: '{NICKNAME}',
        tag: 'playergirl3',
        rarity: 5,
        path: 'Shaman',
        element: 'Imaginary',
        icon: 'icon/character/8006.png',
        preview: 'image/character_preview/8006.png',
        portrait: 'image/character_portrait/8006.png',
      },
      {
        id: '8007',
        name: '{NICKNAME}',
        tag: 'playerboy4',
        rarity: 5,
        path: 'Memory',
        element: 'Ice',
        icon: 'icon/character/8007.png',
        preview: 'image/character_preview/8007.png',
        portrait: 'image/character_portrait/8007.png',
      },
      {
        id: '8008',
        name: '{NICKNAME}',
        tag: 'playergirl4',
        rarity: 5,
        path: 'Memory',
        element: 'Ice',
        icon: 'icon/character/8008.png',
        preview: 'image/character_preview/8008.png',
        portrait: 'image/character_portrait/8008.png',
      },
    ],
  });
  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
